version: "3.9"
services:
  blog-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/blog
    networks:
      - dev-network  

networks:
  dev-network:
    driver: bridge
