index:
    path: /
    controller:  App\Core\Controller\DefaultController
    method: index

login:
    path: auth
    controller: App\Controller\AuthController
    method: login

login_index:
    path: auth
    controller: App\Controller\AuthController
    method: index
