foo_route_home:
    path:     /
    defaults: { controller: 'App\Controller\HomeController::index' }

foo_route:
    path:     /foo/test/{parametru}/{id}
    defaults: { controller: 'App\Controller\FooController::test' }
    requirements:
        id: '[0-9]+'


#foo_route_test:
#    path:     /foo/test/{id}/{ceva}
#    defaults: { controller: 'App\Controller\FooController::test' }
#    requirements:
#        id: '[0-9]+'
#
#foo_placeholder_route:
#    path:     /foo/{id}
#    defaults: { controller: 'App\Controller\FooController::loadAction' }
#    requirements:
#        id: '[0-9]+'
